### ISSUE TITLE
Realsense cannot be instantiated more than once with multiprocessing

### ISSUE THREAD

**Issue by m-decoster** [airo-ugent/airo-mono#116]
**Describe the bug**

`RuntimeError: Frame didn't arrive within 5000`

This is the same issue as #109 which was fixed in #115 for single process code.

The fix does not work when used with the `multiprocessing` package

**To Reproduce**

Below script:

```
# Set up multiprocessing camera.
namespace = "camera"

# Creating and starting the publisher
p = MultiprocessRGBPublisher(
    Realsense,
    camera_kwargs={
        "resolution": Realsense.RESOLUTION_720,
        "fps": 30,
        "enable_hole_filling": True,
    },
    shared_memory_namespace=namespace,
)
p.start()

self._camera = MultiprocessRGBReceiver(namespace)
self._rerun_logger = MultiprocessRGBRerunLogger(namespace)
self._rerun_logger.start()
```

Realsense will fail to send frames

**Expected behavior**

This should start and log images to rerun, but it only does so after replugging the USB cable (as was the case in the original issue)

**Comment by tlpss** [comment]
hm weird that it no longer works for the multiprocessing case. Could it be due to faulty resource management somehow? (i.e. closing the receivers without properly closing the camera?) @Victorlouisdg  any thoughts?

**Comment by tlpss** [comment]
maybe related to #98

**Comment by Victorlouisdg** [comment]
There's a few things we can investigate:
* are you sure the publisher process has terminated and thus released the handle on the camera hardware?
* if it was terminated: was the `__exit__` method of the `RealSense` object called and thus `pipeline.stop()`?
* if that was called, is the devices listed in the call to `devices = ctx.query_devices()` used by the fix?

**Comment by m-decoster** [comment]
I haven't encountered this issue any more since the `spawn` multiprocessing method is used.
