### ISSUE TITLE
Catch RTDE exceptions in URrtde constructor

### ISSUE THREAD

**Issue by Victorlouisdg** [airo-ugent/airo-mono#143]
Sometimes connecting the to robot fails with weird errors. This often happens after protective stops or emergency stops. Restarting your script usually solves this. However it would be nice if airo-mono tries a few times itself, e.g:
```python
max_attempts = 3
for i in range(max_attempts):
    try:
        gripper_left = Robotiq2F85(ip_address_left)
        robot_left = URrtde(ip_address_left, URrtde.UR3E_CONFIG, gripper_left)

        gripper_right = Robotiq2F85(ip_address_right)
        robot_right = URrtde(ip_address_right, URrtde.UR3E_CONFIG, gripper_right)

        dual_arm = DualArmPositionManipulator(robot_left, X_W_LCB, robot_right, X_W_RCB)
        return dual_arm
    except RuntimeError as e:
        print(f"Failed to connect to UR5e robots. Attempt {i+1}/{max_attempts}. Error:\n {e}")
        if i == max_attempts - 1:
            raise e
        time.sleep(2)
```
This works for me for the cloth competition, example of it saving me a little time:
![Screenshot from 2024-03-28 10-28-20](https://github.com/airo-ugent/airo-mono/assets/23340946/a3ba5630-c6a8-4c6a-988a-14ed7621a8c4)

**Comment by tlpss** [comment]
I think we should only add this to the 'real' hardware classes? not to the Bimanual interfaces on top of them?

**Comment by Victorlouisdg** [comment]
Agreed.
