### ISSUE TITLE
[airo-camera-toolkit] record tcp poses of calibration to autorun with planner 

### ISSUE THREAD

**Issue by adverley** [airo-ugent/airo-mono#56]
When the planner is fully functional and reliable, we could autocalibrate predefined tcp poses for calibrating cameras.

**Comment by tlpss** [comment]
I think that only works for an approx known camera pose (the marker has to be in view) and environment (some poses might be collisions for the tcp or the board). But we could definitely teleop/guide the robot a first time and then use those poses with the planner for future calibrations in the same setup?

**Comment by adverley** [comment]
Fully agreed. It helps to replicate existing setups (e.g. suppose the
camera on setup A for experiment X is remounted for some reasons).  Other
example; we bumped into the side camera a couple of times for unfoldir on
victorlouise.

**Comment by Victorlouisdg** [comment]
Running the calibration now stores the TCP poses to disk as `calibration_<datetime>/data/tcp_pose_0000.json`, docs [here](https://github.com/airo-ugent/airo-mono/tree/main/airo-camera-toolkit/airo_camera_toolkit/calibration).

**Comment by tlpss** [comment]
> Running the calibration now stores the TCP poses to disk as `calibration_<datetime>/data/tcp_pose_0000.json`, docs [here](https://github.com/airo-ugent/airo-mono/tree/main/airo-camera-toolkit/airo_camera_toolkit/calibration).

closing this
