### ISSUE TITLE
Albumentations installs `opencv-headless` which breaks opencv for `camera-toolkit`

### ISSUE THREAD

**Issue by tlpss** [airo-ugent/airo-mono#71]
camera toolkit package requires opencv-contrib for the fudicial markers. 

Albumentation includes opencv-headless in its wheel. 

PROBLEM.

have to install albumentations w/o binaries, but IDK how to to this in a setup.py file. 
cf https://albumentations.ai/docs/getting_started/installation/

**Comment by adverley** [comment]
explore: setup.py of airo-dataset-tools: terminal `pip uninstall opencv && pip install opencv-contrib`

explore: albumentations install without binaries  (see link of thomas):

`pip install -U albumentations --no-binary qudida,albumentations`. 

-> pass flag --no-binary in setup.py.

**Comment by tlpss** [comment]
fixed with #80
