### ISSUE TITLE
Implement force control

### ISSUE THREAD

**Issue by fwyffels** [airo-ugent/airo-mono#73]
Any reasons why we didn't implement the forceMode and forceModeStop functions and additional config functions including forceModeSetDamping and forceModeSetGainScaling

**Comment by Victorlouisdg** [comment]
The current way to access this UR-specific functionality is through the .`rtde_control` and `.rtde_receive` attributes of the airo-mono `URrtde` class, these give direct access to the entire [ur_rtde::RTDEControlInterface](https://sdurobotics.gitlab.io/ur_rtde/api/api.html?highlight=forcemode#_CPPv4N7ur_rtde20RTDEControlInterfaceE):

```python
ur3e = URrtde(...)
ur3e.rtde_control.forceMode()
```
The airo-mono `URrtde` class currently implements only the functions required by the `PositionManipulator` interface.
Force mode and related functionalities do not really fit into the `PositionManipulator` interface and are (mostly) specific to Universal Robots. We could decide to wrap more `ur_rtde` functions in our `URrtde` class, but there's a tradeoff between the slight additional convenience and the additional code to maintain.
