### ISSUE TITLE
COCO resize tools does not work for datasets without keypoints

### ISSUE THREAD

**Issue by Victorlouisdg** [airo-ugent/airo-mono#92]
**Describe the bug**
COCO resize tools does not work for instance datasets yet.

**To Reproduce**

1. Go to `airo-mono/airo-dataset-tools/test/test-data/`
2. Run `airo-dataset-tools resize-coco-keypoints-dataset instances_val2017_small.json --width 50 --height 100`

**Comment by tlpss** [comment]
fixed in #99
